### ISSUE TITLE
Update metadata loads

### ISSUE THREAD

**Issue by nfx** [doctrine/oxm#11]
Please provide different annotation loading schemes:

```
public function loadMetadataForClass($className, ClassMetadataInfo $metadata)
{
    $reflClass = $metadata->getReflectionClass();

    $classAnnotations = $this->reader->getClassAnnotations($reflClass);

    if (isset($classAnnotations['Doctrine\OXM\Mapping\XmlEntity'])) {
```

This code doesn't work with DoctrineOXMBundle and Symfony RC4

**Comment by richardfullmer** [comment]
@nfx - do you mean @golovanov's DoctrineOXMBundle?  

There isn't an official DoctrineOXMBundle yet, but the https://github.com/doctrine/oxm project was recently updated to include doctrine common 2.1 compatability, which should help your loading issues

**Comment by nfx** [comment]
Yeap, the @golovanov's bundle :) It's relatively functional now. Thing that OXM misses is the lookup by ids.
