### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by eggyal** [doctrine/oxm#29]
It seems that this project has been abandoned, not just by the maintainers but also by the community at large—very few issues, forks or PRs of late.

Does anyone have any insight into why this project was abandoned?  Has it been superseded by something else?  Is there any interest in resuming development?

**Comment by richardfullmer** [comment]
I'm no longer maintaining it.  I recommend you use the excellent jms serializer.  https://github.com/schmittjoh/serializer
